// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IAuthorFields {
  /** Name */
  name: string;

  /** Bio */
  bio?: string | undefined;
}

export interface IAuthor extends Entry<IAuthorFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "author";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface IBlogPostFields {
  /** Title */
  title: string;

  /** Content */
  content: Document;

  /** Subtitle */
  subtitle: string;

  /** Published Date */
  publishedDate: string;

  /** Slug */
  slug: string;

  /** Tag */
  tag: Entry<{ [fieldId: string]: unknown }>;

  /** Cover Image */
  coverImage: Asset;

  /** Author */
  author: Entry<{ [fieldId: string]: unknown }>;
}

export interface IBlogPost extends Entry<IBlogPostFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "blogPost";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export interface ITagsFields {
  /** Tag Name */
  tagName: string;

  /** slug */
  slug: string;

  /** Description */
  description: Document;
}

export interface ITags extends Entry<ITagsFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "tags";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE = "author" | "blogPost" | "tags";

export type IEntry = IAuthor | IBlogPost | ITags;

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
